version: "3.8"

services:
   frontend-compliance:
      build: ./frontend/frontend-compliance
      container_name: frontend-compliance
      command: sh -c "npm install && npm run dev -- --host"
      ports:
         - "5173:5173"
      volumes:
         - ./frontend/frontend-compliance:/app
         - ./frontend/common-components:/app/common-components
         - /app/node_modules
      networks:
         - app_network
      depends_on:
         - backend

   frontend-crm:
      build: ./frontend/frontend-crm
      container_name: frontend-crm
      command: sh -c "npm install && npm run dev -- --host"
      ports:
         - "5174:5174"
      volumes:
         - ./frontend/frontend-crm:/app
         - ./frontend/common-components:/app/common-components
         - /app/node_modules
      networks:
         - app_network
      depends_on:
         - backend

   backend:
      build: .
      container_name: fastapi_backend
      ports:
         - "8000:8000"
      volumes:
         - ./data:/app/data
         - .:/app
      env_file:
         - .env
      networks:
         - app_network

   pipeline:
      build: ./Pipeline
      container_name: pipeline
      ports:
         - "8001:8001"
      networks:
         - app_network

networks:
   app_network:
      driver: bridge
